config/routes.rb
Pyklocal::Application.routes.draw do

  namespace :merchant do
    get "stores/amazon/fetch", to: "amazon_products#fetch", as: "store_amazon_product"
    get "/", to: "home#index"
    get "stores/products/:product_id/variants", to: "variants#index", as: "stores_products_variants"
    get "stores/products/:product_id/variants/new", to: "variants#new", as: "stores_products_variants_new"
    get "stores/:store_id/orders", to: "orders#index", as: :store_orders

    resources :stores do
      member do
        get 'report'
        get 'invoice/:bookkeeping_document_id/pdf', action: 'invoice_pdf', as: 'invoice_pdf'
        post 'store_report'
        post 'sale_product'
        get 'invoices'
      end
      collection do
        resources :amazon_products do
          collection do
            post :import_collection
          end
        end
        resources :products do
          resources :images
          resources :variants
          resources :product_properties
          get :stock
          collection do
            post :bulk_upload
            get :sample_csv
          end
        end
        resources :orders do
          get :customer
          get :adjustments
          get :payments
          get :approve
          put :cancel
          post :return_item_accept_reject
          resources :customer_return_items do
            collection do
              get :eligible_item
              post :return_multiple_item
            end
          end
          collection do
            get :returns
          end
        end
      end
    end
    resources :products
    resources :return_authorization_reasons
  end

  resources :email_tokens do
    collection do
      get :edit_store
    end
  end

  mount Spree::Core::Engine, at: '/'

  Spree::Core::Engine.routes.draw do
    get "new_store_application", to: "home#new_store_application"
    get "orders" => "home#orders"
    get "refunds" => "home#refund"
    get "order_placed/:id", to: "orders#order_placed", as: "order_placed"

    resources :addresses
    resources :payment_histories
    resources :wishlists
    resources :users_feedbacks
    resources :shop , :only => [:index,:show]
    resources :orders do
      put :ready_to_pick
      put :cancel
      put :apply_coupon_code
      resources :customer_returns
      resources :customer_return_items do
        collection do
          post :return_multiple_item
          get :eligible_item
        end
      end

    end
    resources :return_authorizations
    resources :payment_preferences

    resource :account, :controller => 'users', except: [:index, :new, :edit, :create, :update, :destroy] do
      member do
        get :change_password
      end
    end

    namespace :api do
      namespace :v1 do

        resources :home
        resources :pages, only: [:index]
        resources :client_tokens, only: [:show]
        resources :user_addresses, only: [:show, :update, :create, :destroy]
        resources :wishlists , :only => [:index, :destroy, :create]

        resources :search do
          get :filters, on: :collection
        end

        resources :categories
        resources :customer_return_items do
          get :eligible_item, on: :collection
        end

        resources :store_sessions
        resources :users_feedbacks

        resources :ratings_reviews, only: [:index, :create]

        resources :products do
          post :rate_and_comment
          get :related_product
        end

        concern :order_routes do
          member do
            put :approve
            put :cancel
            put :empty
            put :apply_coupon_code
            post :add_to_cart
            get :refresh_order_summary
            put :cancel_coupon
            post :populate
            put :cancel_coupon_code
            get :get_adjustments
            get :refunds
          end

          resources :line_items
          resources :payments do
            member do
              put :authorize
              put :capture
              put :purchase
              put :void
              put :credit
            end
          end

          resources :addresses, only: [:show, :update]

          resources :return_authorizations do
            member do
              put :add
              put :cancel
              put :receive
            end
          end
        end

        resources :countries do
          member do
            get :states
          end
        end

        resources :merchant_stores do
          put :update_location
          post :rate
        end
        resources :registrations, only: [:create]
        resources :sessions
        resources :password do
          post :change_password, on: :collection
        end
        resources :users do
          post :user_devices
          get :my_pickup_list
          put :update_location
          put :pickup
          put :add_to_cart
          get :my_cart
          put :remove_from_cart
          put :mark_as_deliver
          get :my_delivery_list
          get :profile
          get :get_cart
          get :get_orders
        end
        resources :orders, concerns: :order_routes

      end
    end

    namespace :admin do
      resources :commissions
      resources :feedbacks
      resources :carousel_images
      resources :info_commercials
      resources :static_images
      resources :cancel_orders

      resources :sellers do
        resources :payment_preferences
        get :stores
        resources :payment_histories
        get :store_orders
        put :activate_store
        put :activate
        put :deactivate
      end
      resources :reports, only: [:index] do
        collection do
          get :products_sale_report
          post :products_sale_report
          get :store_sale_product
          post :products_sale_report
          get :store_details_report
          post :store_details_report
        end
      end
    end

  end

end

app/models/merchant/store_taxon.rb
module Merchant
	class StoreTaxon < ActiveRecord::Base
		self.table_name = "pyklocal_stores_taxons"
	  acts_as_paranoid

		belongs_to :store, class_name: 'Merchant::Store'
		belongs_to :spree_taxon, foreign_key: :taxon_id, class_name: 'Spree::Taxon'
		# after_create :add_subtaxon

		def add_subtaxon
			p "hjhjhjhjhjhjhjhjhj"
			p self.store.id
			p  self.spree_taxon.children.count
			if self.spree_taxon.children.present?
				self.spree_taxon.children.each do |taxon|
					p "898989898989898989898"
					@store_taxon = Merchant::StoreTaxon.where(store_id: self.store.id,taxon_id: taxon.id).new
					@store_taxon.save
				end
			end
		end

	end
end

app/controllers/merchant/amazon_products_controller.rb
require 'uri'
class Merchant::AmazonProductsController < Merchant::ApplicationController

	def fetch
		begin
			@is_owner = true
			if  ["keyword", nil].include?(params[:by])
				
				if params[:keywords].present?
					@amazon_products, @total_results = AMAZON_CLIENT.search_keywords(params[:keywords], {SearchIndex: (params[:serch_index] || "All"), ResponseGroup: (params[:response_type] || "Medium"), ItemPage: (params[:item_page] || 1)})
				elsif params[:node].present?
					@amazon_products = AMAZON_CLIENT.browse_node(params[:node])
				end
			else
				URI.parse(params[:url])
			end
		rescue Exception => e
			redirect_to :back, notice: "Something went wrong. Please try after some time"
		end
		# render json: @amazon_products
	end

	def new
		@is_owner = true
		if params[:asin].blank?
		 redirect_to :back, :params => @params , notice: "please Select Product created"
		else 
			raw_product = AMAZON_CLIENT.lookup(params[:asin]).first
			description = raw_product.try(:editorial_reviews).try(:editorial_review).try(:content)
			if raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100 == 0
				offer_price = raw_product.item_attributes.try(:list_price).try(:amount).to_f/100
			else
				offer_price = raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100
			end
			image_u = raw_product.large_image.try(:url)
			sku = raw_product.item_attributes.title[0..2].upcase+SecureRandom.hex(5).upcase
			asin_no = raw_product.asin
			@product = Spree::Product.where(asin: raw_product.asin, store_id: current_spree_user.stores.first.try(:id)).first
			if @product.blank?
				@product = Spree::Product.create({name: raw_product.item_attributes.title,description: description, price: offer_price, cost_price: offer_price,available_on: Time.zone.now.strftime("%Y/%m/%d"), shipping_category_id: Spree::ShippingCategory.find_by_name("Default").try(:id), image_url: raw_product.large_image.try(:url),store_id: current_spree_user.stores.first.try(:id),asin:asin_no}) 
				@product.sku = sku
				raw_product.item_attributes.each do |amazon_products_properties|
					if amazon_products_properties[1].class.to_s == "REXMLUtiliyNodeString"
	          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
	          product_property = @product.product_properties.build(value: amazon_products_properties[1])
	          product_property.property = property  
	        elsif amazon_products_properties[1].class.to_s == "Array"
	          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
	          amazon_products_properties[1].each do |ap|
	            product_property = @product.product_properties.build({value: ap})
	            product_property.property = property
	          end
	        end
	        @product.save
				end
				raw_product.image_sets.image_set.each do |product_images|
					thumb_image = @product.images.build(attachment: product_images.try(:large_image).try(:url))
					thumb_image.save
				end
				redirect_to edit_merchant_product_path(@product), notice: 'Product successfully added to store'
			else
				redirect_to merchant_stores_path,  notice: 'Could not be saved - this product is already exist!'
					
			end 
		end
	end

	def create
		@is_owner = true
		@product = Spree::Product.new(product_params)
		@product.attributes = product_params.merge({store_id: current_spree_user.stores.first.try(:id)})
		if @product.save
			redirect_to edit_merchant_product_path(@product), notice: "Successfully created"
		else
			@shipping_categories = Spree::ShippingCategory.all
			render :back, notice: 'Could not be saved'
		end
	end

	def import_collection
		success = false
		@is_owner = true
		if params[:product_ids].blank?
			 redirect_to :back, :params => @params , notice: "please Select Product created"
		else 
			AMAZON_CLIENT.lookup(params[:product_ids]).each do |raw_product|
				description = raw_product.try(:editorial_reviews).try(:editorial_review).try(:content)
				if raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100 == 0
					offer_price = raw_product.item_attributes.try(:list_price).try(:amount).to_f/100
				else
					offer_price = raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100
				end
				image_u = raw_product.large_image.try(:url)
				sku = raw_product.item_attributes.title[0..2].upcase+SecureRandom.hex(5).upcase
				asin_no = raw_product.asin
				p "*************************************************************************************8"
				p sku
				@product = Spree::Product.where(asin: raw_product.asin,store_id: current_spree_user.stores.first.try(:id)).first
				if @product.blank?
					@product = Spree::Product.create({name: raw_product.item_attributes.title, sku: sku, description: description, price: offer_price,cost_price: offer_price, available_on: Time.zone.now.strftime("%Y/%m/%d"), shipping_category_id: Spree::ShippingCategory.find_by_name("Default").try(:id), image_url: raw_product.large_image.try(:url), store_id: current_spree_user.stores.first.try(:id), asin: asin_no}) 
					raw_product.item_attributes.each do |amazon_products_properties|
						if amazon_products_properties[1].class.to_s == "REXMLUtiliyNodeString"
		          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
		          product_property = @product.product_properties.build(value: amazon_products_properties[1])
		          product_property.property = property  
		        elsif amazon_products_properties[1].class.to_s == "Array"
		          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
		          amazon_products_properties[1].each do |ap|
		            product_property = @product.product_properties.build({value: ap})
		            product_property.property = property
		          end
		        end
		        if @product.save
		        	success = true
		        else
		        	p "__________________________________________"
		        	p @product.errors.full_messages.join(', ')
		        end
					end
					raw_product.image_sets.image_set.each do |product_images|
						thumb_image = @product.images.build(attachment: product_images.try(:large_image).try(:url))
						thumb_image.save
					end
				else
					redirect_to merchant_stores_path,  notice: 'Could not be saved - this product is already exist!'
					return 	
				end
			end
			if success
				redirect_to merchant_stores_path, notice: 'Product are Successfully added !'
				return
			else
				redirect_to merchant_stores_path, notice: 'Something went wrong'
			end 
		end

	end

	private

		def product_params
			params.require(:product).permit(:name, :sku, :price, :prototype_id, :available_on,:asin,:brand, :shipping_category_id, :image_url, :description, variant_images_attributes: [:attachment], product_properties_attributes: [:value, :id, :property_id, :product_id, property_attributes: [:id, :name, :presentation]])
		end

end

app/controllers/merchant/application_controller.rb
class Merchant::ApplicationController < ActionController::Base
  
	before_filter :authenticate_user!

  protect_from_forgery with: :exception
	
	include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::RespondWith
  include Spree::Core::ControllerHelpers::Search
  include Spree::Core::ControllerHelpers::StrongParameters
  helper Spree::BaseHelper
  helper Spree::OrdersHelper
  helper Spree::ProductsHelper
  helper Spree::StoreHelper
  helper Spree::TaxonsHelper

  before_filter :load_initials

  layout 'merchant'

  def load_initials
    @categories = Spree::Taxon.includes(children: {children: :children}).where(name: "Category").first.try(:children)
    @price_index_bitcoin = price_index_bitcoin
  end

  def price_index_bitcoin
    if ["staging", "production"].include?(Rails.env)
      JSON.parse(open('https://coinbase.com/api/v1/prices/spot_rate').read)["amount"].to_f
    else
      623.5
    end
  end

  def is_active_store
    if current_spree_user && (current_spree_user.stores && !current_spree_user.stores.first.active)
      redirect_to merchant_pyklocal_store_path(id: current_spree_user.stores.first.id), notice: "Your store approval is pending"
    end
  end

  def is_owner?(store)
    if current_spree_user
      current_spree_user.stores.include?(store)
    else
      false
    end
  end

  def try_spree_current_user
    current_spree_user
  end

  def current_currency
    
  end

  def authenticate_user!
    unless current_spree_user && current_spree_user.has_spree_role?("merchant")
      redirect_to spree.login_path, notice: "You are not authorized to access this page."
    end
  end

end

app/controllers/merchant/home_controller.rb
class Merchant::HomeController < Merchant::ApplicationController

	def index
		@stores = current_spree_user.try(:stores)
	end
	
end

app/controllers/merchant/images_controller.rb
class Merchant::ImagesController < Merchant::ApplicationController

	layout 'merchant'
	before_filter :find_image, only: [:destroy, :edit, :update]
	before_filter :load_product

	def index
		@images = @product.variant_images
	end

	def new
		@image = Spree::Image.new
		@variants = @product.variants.map do |variant|
      [variant.sku_and_options_text, variant.id]
    end
    @variants.insert(0, [Spree.t(:all), @product.master.id])
	end

	def edit
		@variants = @product.variants.map do |variant|
      [variant.sku_and_options_text, variant.id]
    end
    @variants.insert(0, [Spree.t(:all), @product.master.id])
	end

	def create
		unless params[:image][:attachment].blank?
			extension = params[:image][:attachment].original_filename.split('.').second.strip
			if ["jpeg","png","jpg"].include?(extension)
				@image = Spree::Image.new(image_params)
				if @image.save
					redirect_to merchant_product_images_path(@product), notice: "Image uploaded successfully"
				else
					render action: 'new'
				end
			else
				redirect_to :back, notice: "Image extension can be jpeg, jpg or png"
			end
		else
			redirect_to :back, notice: "No file selected"
		end
	end

	def update
		if @image.update_attributes(image_params)
			redirect_to merchant_product_images_path(@product), notice: "Images updated successfully"
		else
			render action: 'edit'
		end
	end

	def destroy
		if @image.destroy
			redirect_to  merchant_product_images_path(@product), notice: "Image Deleted successfully"
		else
			redirect_to  merchant_product_images_path(@product), notice: "Something went wrong"
		end
	end

	private

	  def image_params
	  	params.require(:image).permit(:attachment, :viewable_id, :alt, :viewable_type)
	  end

	  def find_image
	  	@image = Spree::Image.where(id: params[:id]).first
	  end

	  def load_product
	  	@product = Spree::Product.where(slug: params[:product_id]).first
	  end

end

app/views/merchant/stores/_store.html.slim
.store-logo-wrapper
	a href="#"
		= image_tag @store.try(:logo).try(:url,:logo)
h4
	strong Store Information
.table-responsive
	table.table.table-condensed.table-responsive.table-user-information
		tbody
			tr
				td
					strong
						span.glyphicon.glyphicon-user.text-primary
						| &nbsp; Store Name:
				td.text-primary
					= @store.try(:name)
			tr
				td
					strong
						span.glyphicon.glyphicon-phone-alt.text-primary
						|&nbsp; Contact no:
				td.text-primary
					= @store.try(:phone_number)
			tr
				td
					strong
						span.glyphicon.glyphicon-home.text-primary
						|&nbsp; Address:
				td.text-primary
					= @store.try(:city)
							 tr
			td
				strong
					span.glyphicon.glyphicon-envelope.text-primary
					| &nbsp;Website:
			td.text-primary
				= @store.try(:site_url)

app/views/merchant/stores/edit.html.slim
/ #container
  .container
    ul.breadcrumb
      li
        a href="/" 
          i.fa.fa-home
          | Home
      li 
        a href=merchant_path
          | Merchant
      li
        span  Edit store

	  / legend Editing store
	  / = render 'form' 
hr/
section.register
  .container-fluid
    .row
      .col-xs-12
        #register
          .modal-dialog role="document"
            .modal-content
              / .modal-header.text-center
              /   h2.modal-title Register Account
              /   h5.modal-sub-title If you already have an account with us, please login at the Login
              .modal-body.vendor-form
                 = render 'form'

app/views/merchant/stores/index.html.slim
#container	
	.container
		ul.breadcrumb
	      li
	        a href="/" 
	          i.fa.fa-home
	          | Home
	      li 
	      	a href=merchant_path
	      		| Merchant

	      li 
	      	a href=new_merchant_store_path
	      		| Store
	      li
	        span  Add New Store
		.row
		  .col-md-12
		    .form-section
			    - if !current_spree_user.has_store
			      .jumbotron
			        h1 Sell with us!
			        p Use our plateform to sell your products.
			        p= link_to "Apply For New Store", new_merchant_store_path, class: "btn btn-primary btn-lg"
				    
			    - elsif current_spree_user.has_store && current_spree_user.active_store
			      .jumbotron
				      h1 Sell with us!
				      p Use our platform to sell your products
				      p= link_to "Go to #{@stores.first.name}", merchant_store_path(id: @stores.first.id), class: "btn btn-primary btn-lg"
			      
			    - else
			      .jumbotron
			        h1 Pending for approval
			        p= "Your store “#{@stores.first.name}” is not approved yet, please wait for approval."
			        p= link_to "Edit #{@stores.first.name}", edit_merchant_store_path(@stores.first.id), class: "btn btn-primary btn-lg"
			      

app/views/merchant/stores/invoices.html.erb
<div id="container">
  <div class="container">
    <ul class="breadcrumb">
      <li>
        <a href="/">
          <i class="fa fa-home"></i>
          Home
        </a>
      </li>
      <li>
        <%= link_to "Merchant", merchant_path %>
      </li>
      <li>
        <%= link_to "Store", merchant_stores_path %>
      </li>
      <li>
        <span>Invoices</span>
      </li>
    </ul>
    <div class="row">
      <div class="left-section col-sm-3">
        <%= render :partial => "merchant/shared/seller" %> 
      </div>

      <div class="right-section col-md-9">
        <div class="table-section">
          <div class="table-headink clearfix">
            <h2>Invoices  </h2>
          </div>
          <div class="order-content">
            <div class="order-row">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr class="no_border" data-hook="printables_index_headers">
                      <th class="trans-head1"><%= sort_link @search, :created_at, Spree.t(:date) %></th>
                      <th class="trans-head2"><%= sort_link @search, :template, Spree.t(:document_type) %></th>
                      <th class="trans-head3"><%= sort_link @search, :number, Spree.t(:number) %></th>
                      <th class="trans-head4"><%= sort_link @search, :firstname, Spree.t(:firstname) %></th>
                      <th class="trans-head5"><%= sort_link @search, :lastname, Spree.t(:lastname) %></th>
                      <th class="trans-head6"><%= sort_link @search, :email, Spree.t(:email) %></th>
                      <th class="trans-head7"><%= sort_link @search, :total, Spree.t(:total) %></th>
                      <th class="trans-head8" data-hook="admin_orders_index_header_actions" class="actions"></th>
                    </tr>
                  </thead>                    
                  <tbody>
                    <% unless @bookkeeping_documents.blank?%>
                      <% @bookkeeping_documents.each do |bookkeeping_document| %>
                        <tr data-hook="admin_printables_index_rows" class="<%= cycle('odd', 'even') %>">
                          <td class="trans-head1"><%= l bookkeeping_document.created_at.to_date %></td>
                          <td class="trans-head2"><%= I18n.t(bookkeeping_document.document_type, scope: [:spree, :print_invoice]) %></td>
                          <td class="trans-head3"><%= bookkeeping_document.number %></td>
                          <td class="trans-head4"><%= bookkeeping_document.firstname %></td>
                          <td class="trans-head5"><%= bookkeeping_document.lastname %></td>
                          <td class="trans-head6"><%= bookkeeping_document.email %></td>
                          <% line_items = Spree::Order.find(bookkeeping_document.printable_id).line_items %>
                          <% total_price = 0.0 %>
                          <% line_items.each do |line_item| %>
                            <% if line_item.product.store_id == @store.id %>
                              <% total_price += line_item.price.to_f %>
                            <% end %>
                          <% end %>
                          <td class="trans-head7"><%= ActionController::Base.helpers.number_to_currency(total_price) %></td>
                          <td class='trans-head8 actions actions-1' data-hook="admin_orders_index_row_actions">
                            <%= link_to '<i class="fa fa-file"></i>'.html_safe, invoice_pdf_merchant_store_path(id: @store.slug, bookkeeping_document_id: bookkeeping_document.id, format: :pdf) %>        
                          </td>
                        </tr>
                      <% end %>                      
                    <% else %>
                      No Invoices Found
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="block-pagination">
              <% if @bookkeeping_documents.respond_to?(:num_pages) %>
                <%= paginate @bookkeeping_documents %>
              <% end %>              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/merchant/stores/new.html.slim
hr/
section.register
  .container-fluid
    .row
      .col-xs-12
        #register
          .modal-dialog role="document"
            .modal-content
              / .modal-header.text-center
              /   h2.modal-title Register Account
              /   h5.modal-sub-title If you already have an account with us, please login at the Login
              .modal-body.vendor-form
                 = render 'form'

/ .container.new-form-wrapper
/   span.form-title 
/     legend Fill the form for New store
/   = render 'form'

app/views/merchant/stores/report.html.slim
#container
  .container
    ul.breadcrumb
        li
          a href="/" 
            i.fa.fa-home
            | Home
        li 
          a href=merchant_path
            | Merchant

        li 
          a href=merchant_store_path(@store)
            | Store
        li
          span 
            = @store.name
        li
        	span
        		| report
    .row
      .col-sm-3
        = render :partial => "merchant/shared/seller"
              / = link_to "Contact Seller", new_message_path(to_user_id: @store.store_spree_users.first.spree_user_id), class: "store-link"
      .col-sm-9
      	.row
      		= form_tag store_report_merchant_store_path(@store, :format => :xlsx), id: "download-report-form"
    				=hidden_field_tag :start_date, @start_date, id: "hidden-start-date"
    				=hidden_field_tag :end_date, @end_date, id: "hidden-end-date"
    				=hidden_field_tag :view_mode, "weekly", id: "hidden-view-mode"
    				=submit_tag "Download as xml", class: "btn btn-primary btn-download"

    		.row
      		= form_tag store_report_merchant_store_path(@store), id: "store-report-form", method: :post, data: {remote: true}
      			.row.form-group
      				.col-sm-6
	      				=label_tag nil, Spree.t(:from)
	      				=text_field_tag :start_date, @start_date, class: "form-control"
      				.col-sm-6
	      				=label_tag nil, Spree.t(:to)
	      				=text_field_tag :end_date, @end_date, class: "form-control"
	      			.col-sm-2.col-sm-offset-10
	      				=select_tag "view_mode", "<option value='daily'>Daily</option><option value='weekly' selected>Weekly</option><option value='monthly'>Monthly</option>".html_safe, class: "form-control view-mode-select"
				.row.store-report-wrapper
					table.table.table-bordered.admin-report data-hook="sales_total"
					  thead
					    tr
					      th= Spree.t(:Duration)
					      th= Spree.t(:total_sale_amount)
					      th= Spree.t(:total_tax)
					      th= Spree.t(:commission)
					      th= "Return Amount"
					      th= "Return Tax"
					      th= "Amount Due"
					  tbody
					    - @store_sale_array.each do |merchant|
					      tr id = merchant[:id]
					      	- duration = merchant[:start_date].to_s + "~" + merchant[:end_date].to_s
					        td 
					          a.store-product-info id = merchant[:id] data-start-date = merchant[:start_date] data-end-date = merchant[:end_date]	
					        		= duration
					        td = merchant[:sales_amount]
					        td = merchant[:tax]
					        td = merchant[:commission]
					        td = merchant[:amount_return]
					        td = merchant[:tax_return]
					        td = merchant[:amount_due]
#store-product-modal.modal.fade[role="dialog"]
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal"]
          | ×
        h4.modal-title
          h3.store-name
      .modal-body
        table.table-responsive.table-bordered.store-product-report
          
      .modal-footer
        button.btn.btn-default[type="button" data-dismiss="modal"]
          | Close					        

app/views/merchant/stores/sale_product.html.slim
h3 = @store.name
- if @product_sale_arr.any? or @return_item_arr.any?
	hr
	table.table.table-bordered.admin-report data-hook="sales_product"
	  thead
	    tr
	      th= Spree.t(:Name)
	      th= Spree.t("Price(USD)")
	      th= Spree.t(:Quantity)
	      th= Spree.t("Tax(Rate %)")
	      th= Spree.t(:Status)
	  tbody
	    - @product_sale_arr.each do |product|
	      tr id = product[:id]
	        td = product[:name]
	        td = product[:price]
	        td = product[:qty]
	        td = product[:tax_rate]
	        td Purchased
	    - @return_item_arr.each do |product|
	      tr id = product[:id]
	        td = product[:name]
	        td = product[:price]
	        td = product[:qty]
	        td = product[:tax_rate]
	        td Return
- else
	span No Products Found

app/views/merchant/stores/show.html.slim
#container
  .container
    ul.breadcrumb
        li
          a href="/" 
            i.fa.fa-home
            | Home
        li 
          a href=merchant_path
            | Merchant

        li 
          a href=merchant_store_path(@store)
            | Store
        li
          span 
            = @store.name
    .row
      .col-sm-3
        = render :partial => "merchant/shared/seller"
              / = link_to "Contact Seller", new_message_path(to_user_id: @store.store_spree_users.first.spree_user_id), class: "store-link"
      .col-sm-9
        br
        #seller-search.input-group
          = form_tag '', :method => 'get', id: "seller-search-box" do 
            input id="seller-search-input" class="form-control" autocomplete="off" name="q[search]" placeholder="Search for..." value=(params[:q][:search] rescue "")
            button.button-search type="submit" 
              i.fa.fa-search
        br 
        br       
        h2 Store Product
        = render partial: "merchant/shared/products", locals: {products: @products}
        hr

      .col-sm-6.text-left
      .col-sm-6
        - if @products.respond_to?(:num_pages)
          = paginate @products

- content_for :js do
  javascript:
    $(document).ready(function(){ 
      var store = "#{@store.is_located?}" == "true" ? true : false; 
      if(!store){
        $("#add-location").trigger("click");
      }
    });

app/views/merchant/stores/store_report.html.slim
table.table.table-bordered.admin-report data-hook="sales_total"
  thead
    tr
      th= Spree.t(:Duration)
      th= Spree.t(:total_sale_amount)
      th= Spree.t(:total_tax)
      th= Spree.t(:commission)
      th= "Return Amount"
      th= "Return Tax"
      th= "Amount Due"
  tbody
    - @store_sale_array.each do |merchant|
      tr id = merchant[:id]
        - duration = ""
        - if @view_mode === "daily" 
          - duration = merchant[:start_date].strftime("%m-%d-%Y")
        - else 
          - duration = merchant[:start_date].strftime("%m-%d-%Y") + "~" + merchant[:end_date].strftime("%m-%d-%Y")
        td 
          a.store-product-info id = merchant[:id] data-start-date = merchant[:start_date] data-end-date = merchant[:end_date]
            = duration
        td = merchant[:sales_amount]
        td = merchant[:tax]
        td = merchant[:commission]
        td = merchant[:amount_return]
        td = merchant[:tax_return]
        td = merchant[:amount_due]      