config/routes.rb
Pyklocal::Application.routes.draw do

  namespace :merchant do
    get "stores/amazon/fetch", to: "amazon_products#fetch", as: "store_amazon_product"
    get "/", to: "home#index"
    get "stores/products/:product_id/variants", to: "variants#index", as: "stores_products_variants"
    get "stores/products/:product_id/variants/new", to: "variants#new", as: "stores_products_variants_new"
    get "stores/:store_id/orders", to: "orders#index", as: :store_orders

    resources :stores do
      member do
        get 'report'
        get 'invoice/:bookkeeping_document_id/pdf', action: 'invoice_pdf', as: 'invoice_pdf'
        post 'store_report'
        post 'sale_product'
        get 'invoices'
      end
      collection do
        resources :amazon_products do
          collection do
            post :import_collection
          end
        end
        resources :products do
          resources :images
          resources :variants
          resources :product_properties
          get :stock
          collection do
            post :bulk_upload
            get :sample_csv
          end
        end
        resources :orders do
          get :customer
          get :adjustments
          get :payments
          get :approve
          put :cancel
          post :return_item_accept_reject
          resources :customer_return_items do
            collection do
              get :eligible_item
              post :return_multiple_item
            end
          end
          collection do
            get :returns
          end
        end
      end
    end
    resources :products
    resources :return_authorization_reasons
  end

  resources :email_tokens do
    collection do
      get :edit_store
    end
  end

  mount Spree::Core::Engine, at: '/'

  Spree::Core::Engine.routes.draw do
    get "new_store_application", to: "home#new_store_application"
    get "orders" => "home#orders"
    get "refunds" => "home#refund"
    get "order_placed/:id", to: "orders#order_placed", as: "order_placed"

    resources :addresses
    resources :payment_histories
    resources :wishlists
    resources :users_feedbacks
    resources :shop , :only => [:index,:show]
    resources :orders do
      put :ready_to_pick
      put :cancel
      put :apply_coupon_code
      resources :customer_returns
      resources :customer_return_items do
        collection do
          post :return_multiple_item
          get :eligible_item
        end
      end

    end
    resources :return_authorizations
    resources :payment_preferences

    resource :account, :controller => 'users', except: [:index, :new, :edit, :create, :update, :destroy] do
      member do
        get :change_password
      end
    end

    namespace :api do
      namespace :v1 do

        resources :home
        resources :pages, only: [:index]
        resources :client_tokens, only: [:show]
        resources :user_addresses, only: [:show, :update, :create, :destroy]
        resources :wishlists , :only => [:index, :destroy, :create]

        resources :search do
          get :filters, on: :collection
        end

        resources :categories
        resources :customer_return_items do
          get :eligible_item, on: :collection
        end

        resources :store_sessions
        resources :users_feedbacks

        resources :ratings_reviews, only: [:index, :create]

        resources :products do
          post :rate_and_comment
          get :related_product
        end

        concern :order_routes do
          member do
            put :approve
            put :cancel
            put :empty
            put :apply_coupon_code
            post :add_to_cart
            get :refresh_order_summary
            put :cancel_coupon
            post :populate
            put :cancel_coupon_code
            get :get_adjustments
            get :refunds
          end

          resources :line_items
          resources :payments do
            member do
              put :authorize
              put :capture
              put :purchase
              put :void
              put :credit
            end
          end

          resources :addresses, only: [:show, :update]

          resources :return_authorizations do
            member do
              put :add
              put :cancel
              put :receive
            end
          end
        end

        resources :countries do
          member do
            get :states
          end
        end

        resources :merchant_stores do
          put :update_location
          post :rate
        end
        resources :registrations, only: [:create]
        resources :sessions
        resources :password do
          post :change_password, on: :collection
        end
        resources :users do
          post :user_devices
          get :my_pickup_list
          put :update_location
          put :pickup
          put :add_to_cart
          get :my_cart
          put :remove_from_cart
          put :mark_as_deliver
          get :my_delivery_list
          get :profile
          get :get_cart
          get :get_orders
        end
        resources :orders, concerns: :order_routes

      end
    end

    namespace :admin do
      resources :commissions
      resources :feedbacks
      resources :carousel_images
      resources :info_commercials
      resources :static_images
      resources :cancel_orders

      resources :sellers do
        resources :payment_preferences
        get :stores
        resources :payment_histories
        get :store_orders
        put :activate_store
        put :activate
        put :deactivate
      end
      resources :reports, only: [:index] do
        collection do
          get :products_sale_report
          post :products_sale_report
          get :store_sale_product
          post :products_sale_report
          get :store_details_report
          post :store_details_report
        end
      end
    end

  end

end

app/controllers/merchant/orders_controller.rb
class Merchant::OrdersController < Merchant::ApplicationController

	before_filter :is_active_store
  before_filter :find_order, only: [:edit, :update, :validate_actions, :customer, :adjustments, :payments, :returns, :approve, :cancel, :return_item_accept, :return_item_reject]

	def index
    @store = current_spree_user.stores.first
    if @store.present?
      params[:q] = {} unless params[:q]
      if params[:q][:orders_completed_at_gt].blank?
        params[:q][:orders_completed_at_gt] = Time.zone.now.beginning_of_month
      else
        params[:q][:orders_completed_at_gt] = Time.zone.parse(params[:q][:orders_completed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
      end

      if params[:q] && !params[:q][:orders_completed_at_lt].blank?
        params[:q][:orders_completed_at_lt] = Time.zone.parse(params[:q][:orders_completed_at_lt]).end_of_day rescue ""
      end

      params[:q][:s] ||= "completed_at desc"

      if params[:q][:search].present?
        @search = @store.orders.complete.where("number LIKE ?", "%#{params[:q][:search]}%").uniq.ransack(params[:q])
      else
        @search = @store.orders.complete.uniq.ransack(params[:q])
      end

      @orders = Kaminari.paginate_array(@search.result).page(params[:page]).per(10)
      @is_owner = is_owner?(@store)
    else
      @orders = nil
    end
  end

  def new
  	if !@current_spree_user.has_spree_role?('admin')
      if @current_spree_user.has_spree_role?('merchant')
        raise CanCan::AccessDenied.new
      end
    end  
    @order = Order.create
    @order.created_by = try_spree_current_user
    @order.save
    redirect_to edit_admin_order_url(@order)
  end

  def edit
  	validate_actions
    unless @order.complete?
      @order.refresh_shipment_rates
    end
    @store = current_spree_user.stores.first
  end

  def update
  	validate_actions
    if @order.update_attributes(params[:order]) && @order.line_items.present?
      @order.update!
      unless @order.complete?
        # Jump to next step if order is not complete.
        redirect_to admin_order_customer_path(@order) and return
      end
    else
      @order.errors.add(:line_items, Spree.t('errors.messages.blank')) if @order.line_items.empty?
    end

    render :action => :edit
  end

  def cancel
  	# validate_actions
   #  @order.cancel!
   #  flash[:success] = Spree.t(:order_canceled)
   #  redirect_to :back
    if @order.completed_at.to_date + 14.days < Date.today
      redirect_to :back , notice: "Order can only be cancel within 14 days of completion"
    else
      @amount = @order.amount.to_f * 100
      @paypal_refund_object = @order.payments.valid.last.payment_method.credit(@amount,@order.payments.valid.last.response_code,{})
      if @paypal_refund_object.success?
        @paypal_transaction_object = @paypal_refund_object.transaction
        p "*****************************************"
        p @paypal_transaction_object 
        Spree::CustomerReturnItem.where(store_id: @store.id,order_id: @order.id,status: "approved").update_all(transaction_id: @paypal_transaction_object.id,status: "refunded")
        @refund = Spree::Refund.new(payment_id:@order.payments.valid.last.response_code, amount: @paypal_transaction_object.amount * 100, transaction_id: @paypal_transaction_object.id,order_id: @order.id, card_type:@paypal_transaction_object.credit_card_details.card_type, last_card_digits:@paypal_transaction_object.credit_card_details.last_4, expiration:@paypal_transaction_object.credit_card_details.expiration_date, status:@paypal_transaction_object.status)
        if @refund.save
          redirect_to merchant_order_customer_return_items_path(@order),  notice: 'Item(s) Return Successfully'
          return
        else
          redirect_to :back,  notice: 'Something Went Wrong while refunding amount'
          p "*************************************"
          p @refund.errors.full_messages.join(', ')
          return
        end
      else
        p "((((((((((((((((((((((((((((((((((((((((((((((((((((("
        p @paypal_refund_object.errors
        p @paypal_refund_object.errors.first
        Spree::CustomerReturnItem.where(store_id: @store.id,order_id: @order.id,status: "approved").update_all(status: "failed")
        redirect_to :back,  notice: @paypal_refund_object.errors.first.message.to_s
        return
      end
    end
  end

  def customer
    @customer = @order.user
    @bill_address = @order.try(:bill_address)
  end

  def adjustments
    @adjustments = @order.adjustments
  end

  def payments
    @payments = @order.payments
  end

  def returns
    p "((((((((((((((((((((((((((("
    p current_spree_user.stores.first
    @store = current_spree_user.stores.first
    @is_owner = is_owner?(@store)
    @return_orders = @store.customer_return_items.where(status: "refunded").order("created_at desc").collect(&:order_id).uniq
  end

  def approve
    # if @order.update_attributes(approver_id: current_spree_user.id, approved_at: Time.zone.now, considered_risky: false)
    #   redirect_to :back, notice: "Order Approved"
    # else
    #   redirect_to :back, notice: @order.errors.full_messages.join(", ")
    # end
    p "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    p params
    @store = current_spree_user.stores.first
    @is_owner = is_owner?(@store)
    @customer_return_items = []
    @order.customer_return_items.where(status: 'Requested').each do |item|
      if item.line_item.variant.product.store_id == @store.id
        @customer_return_items << item
      end
    end
    p @customer_return_items
  end


  def return_item_accept_reject
    @store = current_spree_user.stores.first
    @is_owner = is_owner?(@store)
     p "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
     p params
    # p params[:commit]
    # p params[:customer_return_items].first["id"]
    # if params[:customer_return_items].present?
    #   if params[:commit] == "Accept"
    #     params[:customer_return_items].each do |return_item|
    #       unless Spree::CustomerReturnItem.find(return_item["id"].to_i).update_attributes(status: 'Accepted')
    #         redirect_to :back ,notice: "Unable to update the status of item"
    #       end
    #     end
    #    # params[:customer]
    #     p "666666666666"
    #   elsif params[:commit] == "Reject"
    #     params[:customer_return_items].each do |return_item|
    #       unless Spree::CustomerReturnItem.find(return_item["id"].to_i).update_attributes(status: 'Rejected')
    #         redirect_to :back ,notice: "Unable to update the status of item"
    #       end
    #     end
    #     p "0000000000"
    #   else
    #     redirect_to :back ,notice: "Wrong Choice of Action"
    #   end
    # else
    #   redirect_to :back, notice: "No item is selected for Approval or Rejection"
    #   return
    # end

    if params[:customer_return_items].blank?
        redirect_to :back, :params => @params , notice: "please Select Item to be returned"
        return
    else
      params[:customer_return_items].each do |approve_item|
         id = approve_item["id"].to_i
         @customer_return_item = Spree::CustomerReturnItem.find(id)
        if @customer_return_item.status == 'Requested'
          if approve_item["id"].present? && approve_item["quantity"].present?
            if approve_item["quantity"].first.blank?
              redirect_to :back, :params => @params , notice: "Quantity can not be blank"
              return
            else
              qty = approve_item["quantity"].first.to_i
              tax_rate = @customer_return_item.line_item.variant.tax_category_id.present? ? @customer_return_item.line_item.variant.tax_category.tax_rates.first.amount.to_f : @customer_return_item.line_item.product.tax_category.tax_rates.first.amount.to_f 
              p "**********************************************************"
              p qty
              p id
              p tax_rate
               return_item_price = (@customer_return_item.line_item.price.to_f * qty).round(2)
              tax_amt = (return_item_price * tax_rate).round(2) 

              if qty == 0
                merchant_status = "Rejected"
                refund_status = "NA"
              elsif qty == @customer_return_item.return_quantity
                merchant_status = "Full Return"
                refund_status = "Full Refund"
              else
                merchant_status = "Partial Return"
                refund_status = "Partial Refund"
              end
              p merchant_status
              p refund_status
              if  @customer_return_item.update_attributes(item_return_amount: return_item_price, tax_amount: tax_amt, total: return_item_price + tax_amt, status: merchant_status, refunded: refund_status, approve_qty: qty)
                # redirect_to :back, :params => @params , notice: "Approve Succesfully"
                # return
              else
                redirect_to :back, :params => @params , notice: "Error Occured While approving the items(s)"
                return
              end
              # @customer_return_item = Spree::CustomerReturnItem.find()
            end
          else
            redirect_to :back, :params => @params , notice: "Please Provide Quantity"
            return
          end
        else
          redirect_to :back, :params => @params , notice: "Item is Already Updated"
          return
        end
      end
    end

    redirect_to :back, :params => @params , notice: "Approved Succesfully"
  end

  def cancel
    validate_actions
    @order.cancel!
    flash[:success] = Spree.t(:order_canceled)
    redirect_to :back
  end

  private 

  	def validate_actions
  		rais_error = true
    	if !@current_spree_user.has_spree_role?('admin')
        if @current_spree_user.has_spree_role?('merchant')
        		@order.line_items.each do |line_item|
        			if line_item.variant.product.store_id == @current_spree_user.stores.first.id
        				rais_error = false
        				break
        			end	
        		end

app/views/spree/admin/orders/_shipment.html.erb
<div id="<%= "shipment_#{shipment.id}" %>" data-hook="admin_shipment_form" class="panel panel-default">

  <%= render partial: "spree/admin/variants/split", formats: :js %>

  <div class="panel-heading stock-location no-borderb" data-hook="stock-location">
    <h1 class="panel-title">
      <span class="shipment-number"><%= shipment.number %></span>
      -
      <span class="shipment-state"><%= Spree.t("shipment_states.#{shipment.state}") %></span>
      <%= Spree.t(:package_from) %>
      <strong class="stock-location-name" data-hook="stock-location-name">'<%= shipment.stock_location.name %>'</strong>
      <% if shipment.ready? and can? :update, shipment %>
        <%= link_to Spree.t(:ship), 'javascript:;', class: 'ship pull-right btn btn-success', data: { 'shipment-number' => shipment.number } %>
        <div class='clearfix'></div>
      <% end %>
    </h1>
  </div>

  <table class="table table-bordered stock-contents" data-hook="stock-contents">
    <thead>
      <th colspan="2"><%= Spree.t(:item_description) %></th>
      <th width="15%" class="text-center"><%= Spree.t(:price) %></th>
      <th width="15%" class="text-center"><%= Spree.t(:quantity) %></th>
      <th width="15%" class="text-center"><%= "Delivery State" %></th>
      <th width="15%" class="text-center"><%= Spree.t(:total) %></th>
      <th class="orders-actions actions text-center" data-hook="admin_order_form_line_items_header_actions"></th>
    </thead>

    <tbody data-shipment-number="<%= shipment.number %>" data-order-number="<%= order.number %>">
      <%= render 'spree/admin/orders/shipment_manifest', shipment: shipment %>

      <% unless shipment.shipped? %>
        <tr class="edit-method is-hidden total">
          <td colspan="5">
            <div class="field alpha five columns">
              <%= label_tag 'selected_shipping_rate_id', Spree.t(:shipping_method) %>
              <%= select_tag :selected_shipping_rate_id,
                    options_for_select(shipment.shipping_rates.map {|sr| ["#{sr.name} #{sr.display_price}", sr.id] }, shipment.selected_shipping_rate_id),
                    { class: 'select2', data: {'shipment-number' => shipment.number } } %>
            </div>
          </td>
          <td class="actions text-center">
            <% if can? :update, shipment %>
              <%= link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", class: 'cancel-method btn btn-primary btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), no_text: true %>
              <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-method btn btn-success btn-sm', data: {'shipment-number' => shipment.number, action: 'save'}, title: Spree.t('actions.save'), no_text: true %>
            <% end %>
          </td>
        </tr>
        <% end %>

        <tr class="show-method total">
          <% if rate = shipment.selected_shipping_rate %>
            <td colspan="4">
              <strong><%= rate.name %></strong>
            </td>
            <td class="total text-center">
              <%= shipment.display_cost %>
            </td>
          <% else %>
            <td colspan='5'><%= Spree.t(:no_shipping_method_selected) %></td>
          <% end %>

          <td class="actions text-center">
            <% if( (can? :update, shipment) and !shipment.shipped?) %>
              <%= link_to_with_icon 'edit', Spree.t('edit'), "javascript:;", class: 'edit-method with-tip btn btn-sm btn-primary', data: {action: 'edit'}, no_text: true %>
            <% end %>
          </td>
        </tr>


      <tr class="edit-tracking is-hidden total">
        <td colspan="5">
          <label><%= Spree.t(:tracking_number) %>:</label>
          <%= text_field_tag :tracking, shipment.tracking, class: "form-control" %>
        </td>
        <td class="actions">
          <% if can? :update, shipment %>
            <%= link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", :class => 'cancel-tracking btn btn-primary btn-sm', :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel'), :no_text => true %>
            <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", :class => 'save-tracking btn btn-success btn-sm', :data => {'shipment-number' => shipment.number, :action => 'save'}, :title => Spree.t('actions.save'), :no_text => true %>
          <% end %>
        </td>
      </tr>

      <% if order.special_instructions.present? %>
        <tr class='special_instructions'>
          <td colspan="5">
            <strong><%= Spree.t(:special_instructions) %>:&nbsp;</strong><%= order.special_instructions %>
          </td>
        </tr>
      <% end %>

      <tr class="show-tracking total">
        <td colspan="5" class="tracking-value">
          <% if shipment.tracking.present? %>
            <strong><%= Spree.t(:tracking) %>:</strong> <%= link_to_tracking(shipment, target: '_blank') %>
          <% else %>
            <%= Spree.t(:no_tracking_present) %>
          <% end %>
        </td>
        <td class="actions text-center">
          <% if can? :update, shipment %>
            <%= link_to_with_icon 'edit', Spree.t('edit'), "#", class: 'edit-tracking btn btn-primary btn-sm', data: {action: 'edit'}, title: Spree.t('edit'), no_text: true %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

</div>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_order), new_admin_order_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_order' %>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="date-range-filter col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
            <div class="row no-padding-bottom">
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from form-control', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>

              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to form-control', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
                  <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_number_cont, Spree.t(:order_number, :number => '') %>
            <%= f.text_field :number_cont, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_state_eq, Spree.t(:status) %>
            <%= f.select :state_eq, Spree::Order.state_machines[:state].states.map {|s| [Spree.t("order_state.#{s.name}"), s.value]}, {:include_blank => true}, :class => 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, Spree.t(:payment_state) %>
            <%= f.select :payment_state_eq, Spree::Order::PAYMENT_STATES.map {|s| [Spree.t("payment_states.#{s}"), s]}, {:include_blank => true}, :class => 'select2 js-filterable' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_shipment_state_eq, Spree.t(:shipment_state) %>
            <%= f.select :shipment_state_eq, Spree::Order::SHIPMENT_STATES.map {|s| [Spree.t("shipment_states.#{s}"), s]}, {:include_blank => true}, :class => 'select2 js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>
            <%= f.text_field :bill_address_firstname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>
            <%= f.text_field :bill_address_lastname_start, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_email_cont, Spree.t(:email) %>
            <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_line_items_variant_sku_eq, Spree.t(:sku) %>
            <%= f.text_field :line_items_variant_sku_eq, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_promotions_id_in, Spree.t(:promotion) %>
            <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), {:include_blank => true}, :class => 'select2' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_stores_id_in, Spree.t(:store) %>
            <%= f.select :stores_id_in, Merchant::Store.pluck(:name, :id), {:include_blank => true}, :class => 'select2' %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">

          <div class="form-group">

            <div class="checkbox">
              <%= label_tag 'q_completed_at_not_null' do %>
                <%= f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '0' %>
                <%= Spree.t(:show_only_complete_orders) %>
              <% end %>
            </div>

            <div class="checkbox">
              <%= label_tag 'q_considered_risky_eq' do %>
                <%= f.check_box :considered_risky_eq, {:checked => (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                <%= Spree.t(:show_only_considered_risky) %>
              <% end %>
            </div>

          </div>

        </div>

      </div>

      <div data-hook="admin_orders_index_search_buttons" class="form-actions">
        <%= button Spree.t(:filter_results), 'search' %>
      </div>

    <% end %>

  </div>

<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders %>

<% if @orders.any? %>
  <table class="table" id="listing_orders" data-hook>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at,   I18n.t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% else %>
          <th><%= sort_link @search, :created_at,     I18n.t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :number,           I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :considered_risky, I18n.t(:considered_risky, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :state,            I18n.t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :payment_state,    I18n.t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
         <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <th><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
         <% end %>
        <th><%= sort_link @search, :email,            I18n.t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :total,            I18n.t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td>
          <%= order_time(@show_only_completed ? order.completed_at : order.created_at) %>
        </td>
        <td><%= link_to order.number, edit_admin_order_path(order) %></td>
        <td>
          <span class="label label-<%= order.considered_risky ? 'considered_risky' : 'considered_safe' %>">
            <%= order.considered_risky ? Spree.t("risky") : Spree.t("safe") %>
          </span>
        </td>
        <td>
          <span class="label label-<%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span>
          <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>"></span>
        </td>
        <td>
          <% if order.payment_state %>
            <span class="label label-<%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_payment_state_eq" data-ransack-value="<%= order.payment_state %>"></span>
          <% end %>
        </td>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <td>
            <% if order.shipment_state %>
              <span class="label label-<%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") %></span>
              <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>"></span>
            <% end %>
          </td>
        <% end %>
        <td>
          <% if order.user %>
            <%= link_to order.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
          <% if order.user || order.email %>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>"></span>
          <% end %>
        </td>
        <td><%= order.display_total.to_html %></td>
        <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>