config/routes.rb
Pyklocal::Application.routes.draw do

  namespace :merchant do
    get "stores/amazon/fetch", to: "amazon_products#fetch", as: "store_amazon_product"
    get "/", to: "home#index"
    get "stores/products/:product_id/variants", to: "variants#index", as: "stores_products_variants"
    get "stores/products/:product_id/variants/new", to: "variants#new", as: "stores_products_variants_new"
    get "stores/:store_id/orders", to: "orders#index", as: :store_orders

    resources :stores do
      member do
        get 'report'
        get 'invoice/:bookkeeping_document_id/pdf', action: 'invoice_pdf', as: 'invoice_pdf'
        post 'store_report'
        post 'sale_product'
        get 'invoices'
      end
      collection do
        resources :amazon_products do
          collection do
            post :import_collection
          end
        end
        resources :products do
          resources :images
          resources :variants
          resources :product_properties
          get :stock
          collection do
            post :bulk_upload
            get :sample_csv
          end
        end
        resources :orders do
          get :customer
          get :adjustments
          get :payments
          get :approve
          put :cancel
          post :return_item_accept_reject
          resources :customer_return_items do
            collection do
              get :eligible_item
              post :return_multiple_item
            end
          end
          collection do
            get :returns
          end
        end
      end
    end
    resources :products
    resources :return_authorization_reasons
  end

  resources :email_tokens do
    collection do
      get :edit_store
    end
  end

  mount Spree::Core::Engine, at: '/'

  Spree::Core::Engine.routes.draw do
    get "new_store_application", to: "home#new_store_application"
    get "orders" => "home#orders"
    get "refunds" => "home#refund"
    get "order_placed/:id", to: "orders#order_placed", as: "order_placed"

    resources :addresses
    resources :payment_histories
    resources :wishlists
    resources :users_feedbacks
    resources :shop , :only => [:index,:show]
    resources :orders do
      put :ready_to_pick
      put :cancel
      put :apply_coupon_code
      resources :customer_returns
      resources :customer_return_items do
        collection do
          post :return_multiple_item
          get :eligible_item
        end
      end

    end
    resources :return_authorizations
    resources :payment_preferences

    resource :account, :controller => 'users', except: [:index, :new, :edit, :create, :update, :destroy] do
      member do
        get :change_password
      end
    end

    namespace :api do
      namespace :v1 do

        resources :home
        resources :pages, only: [:index]
        resources :client_tokens, only: [:show]
        resources :user_addresses, only: [:show, :update, :create, :destroy]
        resources :wishlists , :only => [:index, :destroy, :create]

        resources :search do
          get :filters, on: :collection
        end

        resources :categories
        resources :customer_return_items do
          get :eligible_item, on: :collection
        end

        resources :store_sessions
        resources :users_feedbacks

        resources :ratings_reviews, only: [:index, :create]

        resources :products do
          post :rate_and_comment
          get :related_product
        end

        concern :order_routes do
          member do
            put :approve
            put :cancel
            put :empty
            put :apply_coupon_code
            post :add_to_cart
            get :refresh_order_summary
            put :cancel_coupon
            post :populate
            put :cancel_coupon_code
            get :get_adjustments
            get :refunds
          end

          resources :line_items
          resources :payments do
            member do
              put :authorize
              put :capture
              put :purchase
              put :void
              put :credit
            end
          end

          resources :addresses, only: [:show, :update]

          resources :return_authorizations do
            member do
              put :add
              put :cancel
              put :receive
            end
          end
        end

        resources :countries do
          member do
            get :states
          end
        end

        resources :merchant_stores do
          put :update_location
          post :rate
        end
        resources :registrations, only: [:create]
        resources :sessions
        resources :password do
          post :change_password, on: :collection
        end
        resources :users do
          post :user_devices
          get :my_pickup_list
          put :update_location
          put :pickup
          put :add_to_cart
          get :my_cart
          put :remove_from_cart
          put :mark_as_deliver
          get :my_delivery_list
          get :profile
          get :get_cart
          get :get_orders
        end
        resources :orders, concerns: :order_routes

      end
    end

    namespace :admin do
      resources :commissions
      resources :feedbacks
      resources :carousel_images
      resources :info_commercials
      resources :static_images
      resources :cancel_orders

      resources :sellers do
        resources :payment_preferences
        get :stores
        resources :payment_histories
        get :store_orders
        put :activate_store
        put :activate
        put :deactivate
      end
      resources :reports, only: [:index] do
        collection do
          get :products_sale_report
          post :products_sale_report
          get :store_sale_product
          post :products_sale_report
          get :store_details_report
          post :store_details_report
        end
      end
    end

  end

end

app/models/merchant/store_taxon.rb
module Merchant
	class StoreTaxon < ActiveRecord::Base
		self.table_name = "pyklocal_stores_taxons"
	  acts_as_paranoid

		belongs_to :store, class_name: 'Merchant::Store'
		belongs_to :spree_taxon, foreign_key: :taxon_id, class_name: 'Spree::Taxon'
		# after_create :add_subtaxon

		def add_subtaxon
			p "hjhjhjhjhjhjhjhjhj"
			p self.store.id
			p  self.spree_taxon.children.count
			if self.spree_taxon.children.present?
				self.spree_taxon.children.each do |taxon|
					p "898989898989898989898"
					@store_taxon = Merchant::StoreTaxon.where(store_id: self.store.id,taxon_id: taxon.id).new
					@store_taxon.save
				end
			end
		end

	end
end

app/controllers/merchant/amazon_products_controller.rb
require 'uri'
class Merchant::AmazonProductsController < Merchant::ApplicationController

	def fetch
		begin
			@is_owner = true
			if  ["keyword", nil].include?(params[:by])
				
				if params[:keywords].present?
					@amazon_products, @total_results = AMAZON_CLIENT.search_keywords(params[:keywords], {SearchIndex: (params[:serch_index] || "All"), ResponseGroup: (params[:response_type] || "Medium"), ItemPage: (params[:item_page] || 1)})
				elsif params[:node].present?
					@amazon_products = AMAZON_CLIENT.browse_node(params[:node])
				end
			else
				URI.parse(params[:url])
			end
		rescue Exception => e
			redirect_to :back, notice: "Something went wrong. Please try after some time"
		end
		# render json: @amazon_products
	end

	def new
		@is_owner = true
		if params[:asin].blank?
		 redirect_to :back, :params => @params , notice: "please Select Product created"
		else 
			raw_product = AMAZON_CLIENT.lookup(params[:asin]).first
			description = raw_product.try(:editorial_reviews).try(:editorial_review).try(:content)
			if raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100 == 0
				offer_price = raw_product.item_attributes.try(:list_price).try(:amount).to_f/100
			else
				offer_price = raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100
			end
			image_u = raw_product.large_image.try(:url)
			sku = raw_product.item_attributes.title[0..2].upcase+SecureRandom.hex(5).upcase
			asin_no = raw_product.asin
			@product = Spree::Product.where(asin: raw_product.asin, store_id: current_spree_user.stores.first.try(:id)).first
			if @product.blank?
				@product = Spree::Product.create({name: raw_product.item_attributes.title,description: description, price: offer_price, cost_price: offer_price,available_on: Time.zone.now.strftime("%Y/%m/%d"), shipping_category_id: Spree::ShippingCategory.find_by_name("Default").try(:id), image_url: raw_product.large_image.try(:url),store_id: current_spree_user.stores.first.try(:id),asin:asin_no}) 
				@product.sku = sku
				raw_product.item_attributes.each do |amazon_products_properties|
					if amazon_products_properties[1].class.to_s == "REXMLUtiliyNodeString"
	          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
	          product_property = @product.product_properties.build(value: amazon_products_properties[1])
	          product_property.property = property  
	        elsif amazon_products_properties[1].class.to_s == "Array"
	          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
	          amazon_products_properties[1].each do |ap|
	            product_property = @product.product_properties.build({value: ap})
	            product_property.property = property
	          end
	        end
	        @product.save
				end
				raw_product.image_sets.image_set.each do |product_images|
					thumb_image = @product.images.build(attachment: product_images.try(:large_image).try(:url))
					thumb_image.save
				end
				redirect_to edit_merchant_product_path(@product), notice: 'Product successfully added to store'
			else
				redirect_to merchant_stores_path,  notice: 'Could not be saved - this product is already exist!'
					
			end 
		end
	end

	def create
		@is_owner = true
		@product = Spree::Product.new(product_params)
		@product.attributes = product_params.merge({store_id: current_spree_user.stores.first.try(:id)})
		if @product.save
			redirect_to edit_merchant_product_path(@product), notice: "Successfully created"
		else
			@shipping_categories = Spree::ShippingCategory.all
			render :back, notice: 'Could not be saved'
		end
	end

	def import_collection
		success = false
		@is_owner = true
		if params[:product_ids].blank?
			 redirect_to :back, :params => @params , notice: "please Select Product created"
		else 
			AMAZON_CLIENT.lookup(params[:product_ids]).each do |raw_product|
				description = raw_product.try(:editorial_reviews).try(:editorial_review).try(:content)
				if raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100 == 0
					offer_price = raw_product.item_attributes.try(:list_price).try(:amount).to_f/100
				else
					offer_price = raw_product.try(:offer_summary).try(:lowest_new_price).try(:amount).to_f/100
				end
				image_u = raw_product.large_image.try(:url)
				sku = raw_product.item_attributes.title[0..2].upcase+SecureRandom.hex(5).upcase
				asin_no = raw_product.asin
				p "*************************************************************************************8"
				p sku
				@product = Spree::Product.where(asin: raw_product.asin,store_id: current_spree_user.stores.first.try(:id)).first
				if @product.blank?
					@product = Spree::Product.create({name: raw_product.item_attributes.title, sku: sku, description: description, price: offer_price,cost_price: offer_price, available_on: Time.zone.now.strftime("%Y/%m/%d"), shipping_category_id: Spree::ShippingCategory.find_by_name("Default").try(:id), image_url: raw_product.large_image.try(:url), store_id: current_spree_user.stores.first.try(:id), asin: asin_no}) 
					raw_product.item_attributes.each do |amazon_products_properties|
						if amazon_products_properties[1].class.to_s == "REXMLUtiliyNodeString"
		          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
		          product_property = @product.product_properties.build(value: amazon_products_properties[1])
		          product_property.property = property  
		        elsif amazon_products_properties[1].class.to_s == "Array"
		          property = Spree::Property.where(name: amazon_products_properties[0], presentation: amazon_products_properties[0].titleize).first_or_create
		          amazon_products_properties[1].each do |ap|
		            product_property = @product.product_properties.build({value: ap})
		            product_property.property = property
		          end
		        end
		        if @product.save
		        	success = true
		        else
		        	p "__________________________________________"
		        	p @product.errors.full_messages.join(', ')
		        end
					end
					raw_product.image_sets.image_set.each do |product_images|
						thumb_image = @product.images.build(attachment: product_images.try(:large_image).try(:url))
						thumb_image.save
					end
				else
					redirect_to merchant_stores_path,  notice: 'Could not be saved - this product is already exist!'
					return 	
				end
			end
			if success
				redirect_to merchant_stores_path, notice: 'Product are Successfully added !'
				return
			else
				redirect_to merchant_stores_path, notice: 'Something went wrong'
			end 
		end

	end

	private

		def product_params
			params.require(:product).permit(:name, :sku, :price, :prototype_id, :available_on,:asin,:brand, :shipping_category_id, :image_url, :description, variant_images_attributes: [:attachment], product_properties_attributes: [:value, :id, :property_id, :product_id, property_attributes: [:id, :name, :presentation]])
		end

end

app/controllers/merchant/application_controller.rb
class Merchant::ApplicationController < ActionController::Base
  
	before_filter :authenticate_user!

  protect_from_forgery with: :exception
	
	include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::RespondWith
  include Spree::Core::ControllerHelpers::Search
  include Spree::Core::ControllerHelpers::StrongParameters
  helper Spree::BaseHelper
  helper Spree::OrdersHelper
  helper Spree::ProductsHelper
  helper Spree::StoreHelper
  helper Spree::TaxonsHelper

  before_filter :load_initials

  layout 'merchant'

  def load_initials
    @categories = Spree::Taxon.includes(children: {children: :children}).where(name: "Category").first.try(:children)
    @price_index_bitcoin = price_index_bitcoin
  end

  def price_index_bitcoin
    if ["staging", "production"].include?(Rails.env)
      JSON.parse(open('https://coinbase.com/api/v1/prices/spot_rate').read)["amount"].to_f
    else
      623.5
    end
  end

  def is_active_store
    if current_spree_user && (current_spree_user.stores && !current_spree_user.stores.first.active)
      redirect_to merchant_pyklocal_store_path(id: current_spree_user.stores.first.id), notice: "Your store approval is pending"
    end
  end

  def is_owner?(store)
    if current_spree_user
      current_spree_user.stores.include?(store)
    else
      false
    end
  end

  def try_spree_current_user
    current_spree_user
  end

  def current_currency
    
  end

  def authenticate_user!
    unless current_spree_user && current_spree_user.has_spree_role?("merchant")
      redirect_to spree.login_path, notice: "You are not authorized to access this page."
    end
  end

end

app/controllers/merchant/home_controller.rb
class Merchant::HomeController < Merchant::ApplicationController

	def index
		@stores = current_spree_user.try(:stores)
	end
	
end

app/controllers/merchant/images_controller.rb
class Merchant::ImagesController < Merchant::ApplicationController

	layout 'merchant'
	before_filter :find_image, only: [:destroy, :edit, :update]
	before_filter :load_product

	def index
		@images = @product.variant_images
	end

	def new
		@image = Spree::Image.new
		@variants = @product.variants.map do |variant|
      [variant.sku_and_options_text, variant.id]
    end
    @variants.insert(0, [Spree.t(:all), @product.master.id])
	end

	def edit
		@variants = @product.variants.map do |variant|
      [variant.sku_and_options_text, variant.id]
    end
    @variants.insert(0, [Spree.t(:all), @product.master.id])
	end

	def create
		unless params[:image][:attachment].blank?
			extension = params[:image][:attachment].original_filename.split('.').second.strip
			if ["jpeg","png","jpg"].include?(extension)
				@image = Spree::Image.new(image_params)
				if @image.save
					redirect_to merchant_product_images_path(@product), notice: "Image uploaded successfully"
				else
					render action: 'new'
				end
			else
				redirect_to :back, notice: "Image extension can be jpeg, jpg or png"
			end
		else
			redirect_to :back, notice: "No file selected"
		end
	end

	def update
		if @image.update_attributes(image_params)
			redirect_to merchant_product_images_path(@product), notice: "Images updated successfully"
		else
			render action: 'edit'
		end
	end

	def destroy
		if @image.destroy
			redirect_to  merchant_product_images_path(@product), notice: "Image Deleted successfully"
		else
			redirect_to  merchant_product_images_path(@product), notice: "Something went wrong"
		end
	end

	private

	  def image_params
	  	params.require(:image).permit(:attachment, :viewable_id, :alt, :viewable_type)
	  end

	  def find_image
	  	@image = Spree::Image.where(id: params[:id]).first
	  end

	  def load_product
	  	@product = Spree::Product.where(slug: params[:product_id]).first
	  end

end

app/views/merchant/orders/_index.html.slim
#container
  .container
    ul.breadcrumb
      li
        a href="/" 
          i.fa.fa-home
          | Home
        li 
          a href=merchant_path
            | Merchant

        li 
          a href=merchant_stores_path
            | Store
      li
        span  Store Order History
    .row
      .col-sm-3
        =render :partial => "merchant/shared/seller"
      .col-sm-9
        = render partial: "merchant/shared/order_header", locals: {order: nil}
        #seller-search.input-group
          = form_tag '', :method => 'get', id: "seller-search-box" do 
            input id="seller-search-input" class="form-control" autocomplete="off" name="q[search]" placeholder="Search for..." value=(params[:q][:search] rescue "")
            button.button-search type="submit" 
              i.fa.fa-search
        br 
        br    
        .form-section
          table.table.table-striped
            thead
              tr
                th.order-th = sort_link @search, :number, "Order Number"
                th.order-th = sort_link @search, :completed_at, "Ordered on"
                th.order-th Item Name
                th.order-th Variants
                th.order-th Quantity
                th.order-th = sort_link @search, :total, "Amount"
                th.order-th Delivery Type
                th.order-th Driver Name
                th.order-th Actions
                th.order-th Date & Time
            tbody
              - unless @orders.blank?
                - @orders.each do |order|
                  - if order.completed?
                    - line_item_ids = order.get_home_delivery_line_item_ids(@store.id)
                    tr
                      td.align-middle.order-th rowspan="#{order.get_store_line_items(@store.id).count}"
                        / = link_to order.try(:number), edit_merchant_order_path(order)
                        - if order.get_store_delivered_line_items(@store.id).count == line_item_ids.count
                          = link_to order.try(:number), merchant_order_customer_return_items_path(order), title: "Return Order"
                        - else
                          = order.try(:number)
                      td.order-th rowspan="#{order.get_store_line_items(@store.id).count}"
                        = order.completed_at.strftime("%d-%m-%Y")
                      - order.get_store_line_items(@store.id).each_with_index do |line_item, index|
                        - if index == 0
                          td.order-th= line_item.product.try(:name)
                          td.order-th= line_item.variant.options_text
                          td.order-th= line_item.quantity
                          td.order-th= line_item.price.to_f
                          td.order-th= line_item.delivery_type.try(:humanize)
                          td.order-th= line_item.driver.try(:full_name) || "-"
                          td.align-middle.order-th rowspan="#{order.get_store_line_items(@store.id).count}"
                            - if line_item_ids.present? && order.state != "canceled"
                              - if order.items_state(line_item_ids) == "packaging"
                                = link_to "In process", spree.order_ready_to_pick_path(order, item_ids: line_item_ids, option: "ready_to_pick"), class: "btn btn-success", method: :put
                              - elsif order.items_state(line_item_ids) == "ready_to_pick"
                                = link_to "Ready For Pick Up", spree.order_ready_to_pick_path(order, item_ids: line_item_ids, option: "ready"), class: "btn btn-success", method: :put
                                / = link_to "Cancel", spree.order_ready_to_pick_path(order, item_ids: line_item_ids, option: "packaging"), class: "btn btn-default", method: :put, style: "margin-top: 5px;"
                              - elsif order.items_state(line_item_ids) == "confirmed_pickup"
                                = link_to "Waiting For Driver", spree.order_ready_to_pick_path(order, item_ids: line_item_ids, option: "out_for_delivery"), class: "btn btn-success", method: :put
                              - elsif order.items_state(line_item_ids) == "out_for_delivery"
                                = link_to "Out For Delivery", spree.order_ready_to_pick_path(order, item_ids: line_item_ids, option: "out"), class: "btn btn-success", method: :put
                              - else
                                = link_to "Delivered", "#", class: "btn btn-success order-status", disabled: true
                            -elsif order.state == "canceled"
                              = link_to "Canceled", "#", class: "btn btn-danger"
                          td.order-th
                            - if order.items_state(line_item_ids) == "delivered"
                              = l(order.updated_at, format: '%d/%m/%Y %H-%M')
                        - else
                          tr
                            td.order-th= line_item.product.try(:name)
                            td.order-th= line_item.variant.options_text
                            td.order-th= line_item.quantity
                            td.order-th= line_item.price.to_f
                            td.order-th= line_item.delivery_type.try(:humanize)
                            td.order-th= line_item.driver.try(:full_name) || "-"

              - else
                tr
                  td.order-th colspan="7"
                    span No orders found.
        - if @orders.respond_to?(:num_pages)
          = paginate @orders

app/views/merchant/orders/approve.html.slim
#container
  .container
    ul.breadcrumb
      li
        a href="/" 
          i.fa.fa-home
          | Home
      li
        span  Store Order History
    .row
      .col-sm-3
        =render :partial => "merchant/shared/seller"
      .col-sm-9
        = render partial: "merchant/shared/order_header", locals: {order: nil}
        = form_tag merchant_order_return_item_accept_reject_path(@order),{method: :post} do 
          table.table.table-responsive.table-bordered#return_item 
            thead
              tr
                th.text-center Select
                th.text-center Image
                th.text-center Item(s) Name
                th.text-center Purchased Qty
                th.text-center Returned Qty
                th.text-center Return Qty 
                th.text-center Approve Qty
                th.text-center Unit Price (USD)
                th.text-center Tax Rate (%)
                th.text-center Item Amount (USD)
                th.text-center Tax (USD)
                th.text-center Refund Amount (USD)
              tbody
                  label
                    = check_box_tag 'select-all' , nil , false ,id: "return_item_select_all"
                  |  Select all
                  -unless @customer_return_items.blank?
                    - @customer_return_items.each do |item|
                      - tax_rate = item.line_item.variant.tax_category_id.present? ? item.line_item.variant.tax_category.tax_rates.first.amount.to_f : item.line_item.product.tax_category.tax_rates.first.amount.to_f 
                      tr
                        td 
                          =check_box_tag 'customer_return_items[][id]', item.id, false , class: "return_item_holder"
                        td.text-center data-hook="cart_item_image" 
                          - if item.line_item.variant.images.length == 0
                              = link_to small_image(item.line_item.variant.product),class: "img-price.to_f"                          
                          - else
                            = link_to image_tag(item.line_item.variant.images.first.attachment.url(:mini)),class: "img-thumbnail"
                        td.text-center
                          .variant-name= item.line_item.variant.name
                          / .variant-options= @inventoryunit.variant.options_text
                          / -line_item.product.name
                        td.text-center data-hook="cart_item_quantity"  class = "return_item_td"
                          = item.line_item.quantity
                        td.text-center class = "return_item_td"
                          = @order.customer_return_items.where("status <> ? AND line_item_id = ?", 'Requested', item.line_item_id).sum(:return_quantity)
                        td.text-center data-hook="cart_item_quantity" class = "return_item_td" 
                          = item.return_quantity
                        td.text-center data-hook="cart_item_quantity" style="width: 100px"
                          .input-group.btn-block style=("max-width: 100px;")
                            = number_field 'customer_return_items[][quantity]', nil, min: 0, max: item.return_quantity ,item_id: item.id ,class: "form-control text-center line_item_quantity selectbox-#{item.id}", size: 5, disabled: true
                        td.text-center data-hook="cart_item_price" class = "unit-price-#{item.id} return_item_td"
                          = item.line_item.price
                        td.text-center class = "tax-rate-#{item.id} return_item_td"
                          = tax_rate * 100
                        td.text-center class = "item-price-#{item.id} return_item_td"
                          | 0.00
                        td.text-center class = "tax-#{item.id} return_item_td" 
                          | 0.00
                        td.text-center data-hook="cart_item_price" class = "total-#{item.id} return_item_td"
                          | 0.00
                  - else
                    tr
                      td colspan="12"
                        span No orders found.

          .pull-right
            =submit_tag 'Approve',class: "btn btn-success"
            / =submit_tag 'Reject',class: "btn btn-danger"
            = link_to returns_merchant_orders_path, class: "btn btn-default", style: "margin-left: 5px;", "data-no-turbolink" => true do 
              span.fa.fa-arrow-left
              |  Back to return orders
-content_for :js do 
  javascript:
    $(document).on('change','input[type="checkbox"]',function(){
      if ($(this).is(':checked')){
        $('.selectbox-'+$(this).val()).attr('disabled',false);
      } else {
        $('.selectbox-'+$(this).val()).attr('disabled',true);
      }
    });

    $(document).on('click','#return_item_select_all',function(){
      if ($(this).is(':checked')) {
        $('.return_item_holder').each(function(){
          $(this).prop('checked', true); 
          $(this).change();
        });
      } else {
        $('.return_item_holder').each(function(){
          $(this).prop('checked', false); 
          $(this).change();
        });
      }
    });

    $(document).on('keyup', 'input[type="number"]',function(){
      var qty = ($(this).val()) == null || $(this).val() == '' ? 0 : $(this).val()
      var item_price = parseFloat(($('.unit-price-' + $(this).attr("item_id")).text())) * qty
      tax = (item_price * parseFloat(($('.tax-rate-' + $(this).attr("item_id")).text()))) / 100
      $('.item-price-' + $(this).attr("item_id")).text(item_price.toFixed(2));
      $('.tax-' + $(this).attr("item_id")).text(tax.toFixed(2));
      $('.total-' + $(this).attr("item_id")).text((tax + item_price).toFixed(2));
    });

app/views/merchant/orders/payments.html.slim
.container
  = render partial: "merchant/shared/order_header", locals: {order: @order}
  .row
    .col-md-12
      .form-section
        .col-md-9
          .row.top-margin-row
            .side-space
              table.table.table-striped.table-bordered
                thead
                  tr
                    th DATE/TIME
                    th AMOUNT
                    th PAYMENT METHOD
                    th PAYMENT STATE
                tbody
                  - unless @payments.blank?
                    - @payments.each do |payment|
                      tr
                        td= link_to payment.created_at.try(:to_time), ""
                        td= number_to_currency(payment.amount)
                        td= payment.payment_method.try(:name)
                        td= payment.state.try(:titleize)
                  - else
                    tr
                      td colspan= "5"
                        span No payment detail found.
        .col-md-3
          = render partial: "merchant/shared/edit_order_sidebar", locals: {order: @order} 

app/views/merchant/orders/returns.html.slim
#container
  .container
    ul.breadcrumb
      li
        a href="/" 
          i.fa.fa-home
          | Home
        li 
          a href=merchant_path
            | Merchant

        li 
          a href=merchant_stores_path
            | Store
      li
        span  Return Order History
    .row
      .col-sm-3
        =render :partial => "merchant/shared/seller"
      .col-sm-9
        = render partial: "merchant/shared/order_header", locals: {order: nil}
        .form-section
          table.table.table-bordered#return_item
            thead
              tr
                th.text-center Order Number
                th.text-center  Customer
                th.text-center  Order Date
                / th.text-center Action
            tbody
              - unless @return_orders.blank?
                - @return_orders.each do |order|
                  - @order = Spree::Order.find(order)
                  tr  
                    td= link_to @order.try(:number),  merchant_order_customer_return_items_path(@order)
                    td= @order.try(:user).try(:full_name)
                    td= @order.completed_at.strftime("%d-%m-%Y")
                    / td= link_to merchant_order_approve_path(order), class: "btn btn-danger", title: "Return Order", method: :get do 
                          i.fa.fa-reply
              - else
                tr
                  td colspan="7"
                    span No orders found.
        / - if @orders.respond_to?(:num_pages)
        /   = paginate @orders